apiVersion: v1
kind: Service
metadata:
  name: simsweb-service
  labels:
    app: simsweb
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31100
      protocol: TCP
  selector:
    app: simsweb

